//=====================================================================================================================================================
// Bing Ads .NET SDK ver. 13.0
// 
// Copyright (c) Microsoft Corporation
// 
// All rights reserved. 
// 
// MS-PL License
// 
// This license governs use of the accompanying software. If you use the software, you accept this license. 
//  If you do not accept the license, do not use the software.
// 
// 1. Definitions
// 
// The terms reproduce, reproduction, derivative works, and distribution have the same meaning here as under U.S. copyright law. 
//  A contribution is the original software, or any additions or changes to the software. 
//  A contributor is any person that distributes its contribution under this license. 
//  Licensed patents  are a contributor's patent claims that read directly on its contribution.
// 
// 2. Grant of Rights
// 
// (A) Copyright Grant- Subject to the terms of this license, including the license conditions and limitations in section 3, 
//  each contributor grants you a non-exclusive, worldwide, royalty-free copyright license to reproduce its contribution, 
//  prepare derivative works of its contribution, and distribute its contribution or any derivative works that you create.
// 
// (B) Patent Grant- Subject to the terms of this license, including the license conditions and limitations in section 3, 
//  each contributor grants you a non-exclusive, worldwide, royalty-free license under its licensed patents to make, have made, use, 
//  sell, offer for sale, import, and/or otherwise dispose of its contribution in the software or derivative works of the contribution in the software.
// 
// 3. Conditions and Limitations
// 
// (A) No Trademark License - This license does not grant you rights to use any contributors' name, logo, or trademarks.
// 
// (B) If you bring a patent claim against any contributor over patents that you claim are infringed by the software, 
//  your patent license from such contributor to the software ends automatically.
// 
// (C) If you distribute any portion of the software, you must retain all copyright, patent, trademark, 
//  and attribution notices that are present in the software.
// 
// (D) If you distribute any portion of the software in source code form, 
//  you may do so only under this license by including a complete copy of this license with your distribution. 
//  If you distribute any portion of the software in compiled or object code form, you may only do so under a license that complies with this license.
// 
// (E) The software is licensed *as-is.* You bear the risk of using it. The contributors give no express warranties, guarantees or conditions.
//  You may have additional consumer rights under your local laws which this license cannot change. 
//  To the extent permitted under your local laws, the contributors exclude the implied warranties of merchantability, 
//  fitness for a particular purpose and non-infringement.
//=====================================================================================================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.BingAds.V13.Bulk
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompressionType", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    public enum CompressionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zip = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GZip = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataScope", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    public enum DataScope : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntityData = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QualityScoreData = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidSuggestionsData = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadEntity", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    public enum DownloadEntity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Campaigns = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroups = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ads = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Keywords = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeKeywords = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeKeywords = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignTargetCriterions = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupTargetCriterions = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeSites = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeSites = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignLocationAdExtensions = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCallAdExtensions = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationAdExtensions = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallAdExtensions = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NegativeKeywordLists = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharedNegativeKeywords = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeKeywordListAssociations = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImageAdExtensions = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignImageAdExtensions = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupImageAdExtensions = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppAdExtensions = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupAppAdExtensions = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAppAdExtensions = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriceAdExtensions = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReviewAdExtensions = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeDynamicSearchAdTargets = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupProductPartitions = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignProductScopes = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignReviewAdExtensions = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupReviewAdExtensions = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalloutAdExtensions = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCalloutAdExtensions = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupCalloutAdExtensions = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SitelinkAdExtensions = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignSitelinkAdExtensions = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupSitelinkAdExtensions = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StructuredSnippetAdExtensions = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignStructuredSnippetAdExtensions = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupStructuredSnippetAdExtensions = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemarketingLists = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupRemarketingListAssociations = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Budgets = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TextAds = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductAds = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppInstallAds = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpandedTextAds = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DynamicSearchAds = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupDynamicSearchAdTargets = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeDynamicSearchAdTargets = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignPriceAdExtensions = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupPriceAdExtensions = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Labels = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignLabels = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupLabels = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TextAdLabels = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordLabels = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeRemarketingListAssociations = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomAudiences = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupCustomAudienceAssociations = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeCustomAudienceAssociations = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InMarketAudiences = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupInMarketAudienceAssociations = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeInMarketAudienceAssociations = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audiences = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupAudienceAssociations = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeAudienceAssociations = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductAdLabels = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppInstallAdLabels = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpandedTextAdLabels = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DynamicSearchAdLabels = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountLocationAdExtensions = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountImageAdExtensions = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountAppAdExtensions = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPriceAdExtensions = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountReviewAdExtensions = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountCalloutAdExtensions = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountSitelinkAdExtensions = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountStructuredSnippetAdExtensions = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponsiveAds = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponsiveAdLabels = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductAudiences = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupProductAudienceAssociations = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeProductAudienceAssociations = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimilarRemarketingLists = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupSimilarRemarketingListAssociations = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeSimilarRemarketingListAssociations = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Experiments = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionAdExtensions = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignActionAdExtensions = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupActionAdExtensions = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountActionAdExtensions = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponsiveSearchAds = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponsiveSearchAdLabels = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAudienceAssociations = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeAudienceAssociations = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCustomAudienceAssociations = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeCustomAudienceAssociations = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignInMarketAudienceAssociations = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeInMarketAudienceAssociations = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignProductAudienceAssociations = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeProductAudienceAssociations = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignRemarketingListAssociations = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeRemarketingListAssociations = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignSimilarRemarketingListAssociations = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeSimilarRemarketingListAssociations = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feeds = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FeedItems = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeStoreCriterions = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PromotionAdExtensions = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPromotionAdExtensions = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignPromotionAdExtensions = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupPromotionAdExtensions = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CombinedLists = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupCombinedListAssociations = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeCombinedListAssociations = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCombinedListAssociations = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeCombinedListAssociations = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Images = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerLists = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupCustomerListAssociations = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeCustomerListAssociations = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCustomerListAssociations = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeCustomerListAssociations = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FilterLinkAdExtensions = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountFilterLinkAdExtensions = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignFilterLinkAdExtensions = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupFilterLinkAdExtensions = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FlyerAdExtensions = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountFlyerAdExtensions = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignFlyerAdExtensions = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupFlyerAdExtensions = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidStrategies = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VideoAdExtensions = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountVideoAdExtensions = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignVideoAdExtensions = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupVideoAdExtensions = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Videos = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisclaimerAdExtensions = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignDisclaimerAdExtensions = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdcustomizerAttribute = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAdcustomizerAttribute = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupAdcustomizerAttribute = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordAdcustomizerAttribute = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignConversionGoal = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupHotelListingGroups = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssetGroups = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AudienceGroups = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeWebpages = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AudienceGroupAssetGroupAssociations = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssetGroupListingGroups = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogoAdExtensions = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountLogoAdExtensions = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignLogoAdExtensions = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupLogoAdExtensions = 154,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeadFormAdExtensions = 155,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountLeadFormAdExtensions = 156,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignLeadFormAdExtensions = 157,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNegativeKeywordList = 158,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNegativeKeywordListAssociation = 159,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNegativeKeyword = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConversionGoal = 161,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventGoal = 162,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppInstallGoal = 163,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiStageGoal = 164,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DurationGoal = 165,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfflineConversionGoal = 166,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UrlGoal = 167,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InStoreTransactionGoal = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PagesViewedPerVisitGoal = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmartGoal = 170,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InStoreVisitGoal = 171,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductGoal = 172,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeasonalityAdjustments = 173,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataExclusions = 174,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrandList = 175,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrandItem = 176,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignBrandListAssociation = 177,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssetGroupSearchThemes = 178,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImpressionBasedRemarketingList = 179,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupImpressionBasedRemarketingListAssociations = 180,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeImpressionBasedRemarketingListAssociations = 181,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignImpressionBasedRemarketingListAssociations = 182,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeImpressionBasedRemarketingListAssociations = 183,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssetGroupUrlTargets = 184,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewCustomerAcquisitionGoal = 185,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConversionValueRule = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPlacementExclusionList = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPlacementExclusionListItem = 188,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAccountPlacementExclusionListAssociation = 189,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPlacementInclusionList = 190,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountPlacementInclusionListItem = 191,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAccountPlacementInclusionListAssociation = 192,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Topic = 193,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentPlacement = 194,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrandKit = 195,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadFileType", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    public enum DownloadFileType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Csv = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tsv = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationFault", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail))]
    public partial class ApplicationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingId
        {
            get
            {
                return this.TrackingIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TrackingIdField, value) != true))
                {
                    this.TrackingIdField = value;
                    this.RaisePropertyChanged("TrackingId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFaultDetail", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    [System.SerializableAttribute()]
    public partial class ApiFaultDetail : Microsoft.BingAds.V13.Bulk.ApplicationFault
    {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.BatchError> BatchErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> OperationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.BatchError> BatchErrors
        {
            get
            {
                return this.BatchErrorsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BatchErrorsField, value) != true))
                {
                    this.BatchErrorsField = value;
                    this.RaisePropertyChanged("BatchErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> OperationErrors
        {
            get
            {
                return this.OperationErrorsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true))
                {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiFaultDetail : Microsoft.BingAds.V13.Bulk.ApplicationFault
    {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.AdApiError> ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.AdApiError> Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true))
                {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiError", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailField, value) != true))
                {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchError", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.BingAds.V13.Bulk.EditorialError))]
    public partial class BatchError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailsField, value) != true))
                {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldPath
        {
            get
            {
                return this.FieldPathField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FieldPathField, value) != true))
                {
                    this.FieldPathField = value;
                    this.RaisePropertyChanged("FieldPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMap
        {
            get
            {
                return this.ForwardCompatibilityMapField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ForwardCompatibilityMapField, value) != true))
                {
                    this.ForwardCompatibilityMapField = value;
                    this.RaisePropertyChanged("ForwardCompatibilityMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                if ((this.IndexField.Equals(value) != true))
                {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationError", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    [System.SerializableAttribute()]
    public partial class OperationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailsField, value) != true))
                {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditorialError", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    [System.SerializableAttribute()]
    public partial class EditorialError : Microsoft.BingAds.V13.Bulk.BatchError
    {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AppealableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisapprovedTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReasonCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Appealable
        {
            get
            {
                return this.AppealableField;
            }
            set
            {
                if ((this.AppealableField.Equals(value) != true))
                {
                    this.AppealableField = value;
                    this.RaisePropertyChanged("Appealable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisapprovedText
        {
            get
            {
                return this.DisapprovedTextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DisapprovedTextField, value) != true))
                {
                    this.DisapprovedTextField = value;
                    this.RaisePropertyChanged("DisapprovedText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocationField, value) != true))
                {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublisherCountry
        {
            get
            {
                return this.PublisherCountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PublisherCountryField, value) != true))
                {
                    this.PublisherCountryField = value;
                    this.RaisePropertyChanged("PublisherCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                if ((this.ReasonCodeField.Equals(value) != true))
                {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignScope", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    [System.SerializableAttribute()]
    public partial class CampaignScope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentAccountIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CampaignId
        {
            get
            {
                return this.CampaignIdField;
            }
            set
            {
                if ((this.CampaignIdField.Equals(value) != true))
                {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentAccountId
        {
            get
            {
                return this.ParentAccountIdField;
            }
            set
            {
                if ((this.ParentAccountIdField.Equals(value) != true))
                {
                    this.ParentAccountIdField = value;
                    this.RaisePropertyChanged("ParentAccountId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMode", Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
    public enum ResponseMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorsOnly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorsAndResults = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", ConfigurationName="Microsoft.BingAds.V13.Bulk.IBulkService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IBulkService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByAccountIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByAccountIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByAccountIdsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByAccountIdsApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsResponse DownloadCampaignsByAccountIds(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByAccountIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByAccountIdsResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsResponse> DownloadCampaignsByAccountIdsAsync(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByCampaignIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsResponse DownloadCampaignsByCampaignIds(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByCampaignIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsResponse> DownloadCampaignsByCampaignIdsAsync(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkDownloadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkDownload" +
            "StatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkDownload" +
            "StatusAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkDownload" +
            "StatusApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusResponse GetBulkDownloadStatus(Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkDownloadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkDownload" +
            "StatusResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusResponse> GetBulkDownloadStatusAsync(Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadUrl", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadUr" +
            "lResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadUr" +
            "lAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadUr" +
            "lApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlResponse GetBulkUploadUrl(Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadUrl", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadUr" +
            "lResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlResponse> GetBulkUploadUrlAsync(Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadSt" +
            "atusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadSt" +
            "atusAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadSt" +
            "atusApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusResponse GetBulkUploadStatus(Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/GetBulkUploadSt" +
            "atusResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusResponse> GetBulkUploadStatusAsync(Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UploadEntityRecords", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/UploadEntityRec" +
            "ordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/UploadEntityRec" +
            "ordsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.BingAds.V13.Bulk.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/UploadEntityRec" +
            "ordsApiFaultDetail2Fault", Name="ApiFaultDetail")]
        Microsoft.BingAds.V13.Bulk.UploadEntityRecordsResponse UploadEntityRecords(Microsoft.BingAds.V13.Bulk.UploadEntityRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UploadEntityRecords", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v13/IBulkService/UploadEntityRec" +
            "ordsResponse")]
        System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.UploadEntityRecordsResponse> UploadEntityRecordsAsync(Microsoft.BingAds.V13.Bulk.UploadEntityRecordsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByAccountIdsRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class DownloadCampaignsByAccountIdsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<long> AccountIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public System.Nullable<Microsoft.BingAds.V13.Bulk.CompressionType> CompressionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public Microsoft.BingAds.V13.Bulk.DataScope DataScope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=3)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.DownloadEntity> DownloadEntities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=4)]
        public System.Nullable<Microsoft.BingAds.V13.Bulk.DownloadFileType> DownloadFileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=5)]
        public string FormatVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=6)]
        public System.Nullable<System.DateTime> LastSyncTimeInUTC;
        
        public DownloadCampaignsByAccountIdsRequest()
        {
        }
        
        public DownloadCampaignsByAccountIdsRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, System.Collections.Generic.IList<long> AccountIds, System.Nullable<Microsoft.BingAds.V13.Bulk.CompressionType> CompressionType, Microsoft.BingAds.V13.Bulk.DataScope DataScope, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.DownloadEntity> DownloadEntities, System.Nullable<Microsoft.BingAds.V13.Bulk.DownloadFileType> DownloadFileType, string FormatVersion, System.Nullable<System.DateTime> LastSyncTimeInUTC)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.AccountIds = AccountIds;
            this.CompressionType = CompressionType;
            this.DataScope = DataScope;
            this.DownloadEntities = DownloadEntities;
            this.DownloadFileType = DownloadFileType;
            this.FormatVersion = FormatVersion;
            this.LastSyncTimeInUTC = LastSyncTimeInUTC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByAccountIdsResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class DownloadCampaignsByAccountIdsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public string DownloadRequestId;
        
        public DownloadCampaignsByAccountIdsResponse()
        {
        }
        
        public DownloadCampaignsByAccountIdsResponse(string TrackingId, string DownloadRequestId)
        {
            this.TrackingId = TrackingId;
            this.DownloadRequestId = DownloadRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByCampaignIdsRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class DownloadCampaignsByCampaignIdsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.CampaignScope> Campaigns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public System.Nullable<Microsoft.BingAds.V13.Bulk.CompressionType> CompressionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public Microsoft.BingAds.V13.Bulk.DataScope DataScope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=3)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.DownloadEntity> DownloadEntities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=4)]
        public System.Nullable<Microsoft.BingAds.V13.Bulk.DownloadFileType> DownloadFileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=5)]
        public string FormatVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=6)]
        public System.Nullable<System.DateTime> LastSyncTimeInUTC;
        
        public DownloadCampaignsByCampaignIdsRequest()
        {
        }
        
        public DownloadCampaignsByCampaignIdsRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.CampaignScope> Campaigns, System.Nullable<Microsoft.BingAds.V13.Bulk.CompressionType> CompressionType, Microsoft.BingAds.V13.Bulk.DataScope DataScope, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.DownloadEntity> DownloadEntities, System.Nullable<Microsoft.BingAds.V13.Bulk.DownloadFileType> DownloadFileType, string FormatVersion, System.Nullable<System.DateTime> LastSyncTimeInUTC)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.Campaigns = Campaigns;
            this.CompressionType = CompressionType;
            this.DataScope = DataScope;
            this.DownloadEntities = DownloadEntities;
            this.DownloadFileType = DownloadFileType;
            this.FormatVersion = FormatVersion;
            this.LastSyncTimeInUTC = LastSyncTimeInUTC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByCampaignIdsResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class DownloadCampaignsByCampaignIdsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public string DownloadRequestId;
        
        public DownloadCampaignsByCampaignIdsResponse()
        {
        }
        
        public DownloadCampaignsByCampaignIdsResponse(string TrackingId, string DownloadRequestId)
        {
            this.TrackingId = TrackingId;
            this.DownloadRequestId = DownloadRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkDownloadStatusRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkDownloadStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public string RequestId;
        
        public GetBulkDownloadStatusRequest()
        {
        }
        
        public GetBulkDownloadStatusRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, string RequestId)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkDownloadStatusResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkDownloadStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public int PercentComplete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=3)]
        public string RequestStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=4)]
        public string ResultFileUrl;
        
        public GetBulkDownloadStatusResponse()
        {
        }
        
        public GetBulkDownloadStatusResponse(string TrackingId, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors, System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMap, int PercentComplete, string RequestStatus, string ResultFileUrl)
        {
            this.TrackingId = TrackingId;
            this.Errors = Errors;
            this.ForwardCompatibilityMap = ForwardCompatibilityMap;
            this.PercentComplete = PercentComplete;
            this.RequestStatus = RequestStatus;
            this.ResultFileUrl = ResultFileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadUrlRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkUploadUrlRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public Microsoft.BingAds.V13.Bulk.ResponseMode ResponseMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public long AccountId;
        
        public GetBulkUploadUrlRequest()
        {
        }
        
        public GetBulkUploadUrlRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, Microsoft.BingAds.V13.Bulk.ResponseMode ResponseMode, long AccountId)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.ResponseMode = ResponseMode;
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadUrlResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkUploadUrlResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public string UploadUrl;
        
        public GetBulkUploadUrlResponse()
        {
        }
        
        public GetBulkUploadUrlResponse(string TrackingId, string RequestId, string UploadUrl)
        {
            this.TrackingId = TrackingId;
            this.RequestId = RequestId;
            this.UploadUrl = UploadUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadStatusRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkUploadStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public string RequestId;
        
        public GetBulkUploadStatusRequest()
        {
        }
        
        public GetBulkUploadStatusRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, string RequestId)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadStatusResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class GetBulkUploadStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public int PercentComplete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=3)]
        public string RequestStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=4)]
        public string ResultFileUrl;
        
        public GetBulkUploadStatusResponse()
        {
        }
        
        public GetBulkUploadStatusResponse(string TrackingId, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors, System.Collections.Generic.IList<System.Collections.Generic.KeyValuePair<string, string>> ForwardCompatibilityMap, int PercentComplete, string RequestStatus, string ResultFileUrl)
        {
            this.TrackingId = TrackingId;
            this.Errors = Errors;
            this.ForwardCompatibilityMap = ForwardCompatibilityMap;
            this.PercentComplete = PercentComplete;
            this.RequestStatus = RequestStatus;
            this.ResultFileUrl = ResultFileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadEntityRecordsRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class UploadEntityRecordsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<string> EntityRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public Microsoft.BingAds.V13.Bulk.ResponseMode ResponseMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public long AccountId;
        
        public UploadEntityRecordsRequest()
        {
        }
        
        public UploadEntityRecordsRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, System.Collections.Generic.IList<string> EntityRecords, Microsoft.BingAds.V13.Bulk.ResponseMode ResponseMode, long AccountId)
        {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.EntityRecords = EntityRecords;
            this.ResponseMode = ResponseMode;
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadEntityRecordsResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v13", IsWrapped=true)]
    public partial class UploadEntityRecordsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=0)]
        public System.Collections.Generic.IList<string> EntityRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=1)]
        public System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=2)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v13", Order=3)]
        public string RequestStatus;
        
        public UploadEntityRecordsResponse()
        {
        }
        
        public UploadEntityRecordsResponse(string TrackingId, System.Collections.Generic.IList<string> EntityRecords, System.Collections.Generic.IList<Microsoft.BingAds.V13.Bulk.OperationError> Errors, string RequestId, string RequestStatus)
        {
            this.TrackingId = TrackingId;
            this.EntityRecords = EntityRecords;
            this.Errors = Errors;
            this.RequestId = RequestId;
            this.RequestStatus = RequestStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBulkServiceChannel : Microsoft.BingAds.V13.Bulk.IBulkService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BulkServiceClient : System.ServiceModel.ClientBase<Microsoft.BingAds.V13.Bulk.IBulkService>, Microsoft.BingAds.V13.Bulk.IBulkService
    {
        
        public BulkServiceClient()
        {
        }
        
        public BulkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BulkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BulkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BulkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsResponse DownloadCampaignsByAccountIds(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsRequest request)
        {
            return base.Channel.DownloadCampaignsByAccountIds(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsResponse> DownloadCampaignsByAccountIdsAsync(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByAccountIdsRequest request)
        {
            return base.Channel.DownloadCampaignsByAccountIdsAsync(request);
        }
        
        public Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsResponse DownloadCampaignsByCampaignIds(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsRequest request)
        {
            return base.Channel.DownloadCampaignsByCampaignIds(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsResponse> DownloadCampaignsByCampaignIdsAsync(Microsoft.BingAds.V13.Bulk.DownloadCampaignsByCampaignIdsRequest request)
        {
            return base.Channel.DownloadCampaignsByCampaignIdsAsync(request);
        }
        
        public Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusResponse GetBulkDownloadStatus(Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusRequest request)
        {
            return base.Channel.GetBulkDownloadStatus(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusResponse> GetBulkDownloadStatusAsync(Microsoft.BingAds.V13.Bulk.GetBulkDownloadStatusRequest request)
        {
            return base.Channel.GetBulkDownloadStatusAsync(request);
        }
        
        public Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlResponse GetBulkUploadUrl(Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlRequest request)
        {
            return base.Channel.GetBulkUploadUrl(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlResponse> GetBulkUploadUrlAsync(Microsoft.BingAds.V13.Bulk.GetBulkUploadUrlRequest request)
        {
            return base.Channel.GetBulkUploadUrlAsync(request);
        }
        
        public Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusResponse GetBulkUploadStatus(Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusRequest request)
        {
            return base.Channel.GetBulkUploadStatus(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusResponse> GetBulkUploadStatusAsync(Microsoft.BingAds.V13.Bulk.GetBulkUploadStatusRequest request)
        {
            return base.Channel.GetBulkUploadStatusAsync(request);
        }
        
        public Microsoft.BingAds.V13.Bulk.UploadEntityRecordsResponse UploadEntityRecords(Microsoft.BingAds.V13.Bulk.UploadEntityRecordsRequest request)
        {
            return base.Channel.UploadEntityRecords(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.BingAds.V13.Bulk.UploadEntityRecordsResponse> UploadEntityRecordsAsync(Microsoft.BingAds.V13.Bulk.UploadEntityRecordsRequest request)
        {
            return base.Channel.UploadEntityRecordsAsync(request);
        }
    }
}
